# Generated by Django 4.1.3 on 2022-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.CharField(max_length=128)),
                ('timestamp', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('campaign', models.IntegerField()),
                ('banner', models.IntegerField()),
                ('content_unit', models.IntegerField()),
                ('network', models.IntegerField()),
                ('browser', models.IntegerField()),
                ('operating_system', models.IntegerField()),
                ('country', models.IntegerField()),
                ('state', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
        ),
    ]
