# Generated by Django 4.1.3 on 2022-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0002_clicks_banner_clicks_browser_clicks_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='id',
        ),
        migrations.AddField(
            model_name='clicks',
            name='click_id',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
