# Generated by Django 4.1.3 on 2022-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0003_remove_clicks_id_clicks_click_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clicks',
            name='click_id',
            field=models.CharField(max_length=128, primary_key=False),
        ),
    ]
